name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup .NET 7 environment
        uses: actions/setup-dotnet@v4
        with:
            dotnet-version: '7.x'
      - name: Build diffcalc DLL
        run: dotnet build
      - name: Save DLL as artifact
        uses: actions/upload-artifact@v4
        with:
            name: DiffCalcDLL
            path: ./TootTallyDiffCalcToPython/bin/Debug/net6.0/TootTallyDiffCalcTTV2.dll
