name: Perform Recalculation

on:
    workflow_dispatch:
    workflow_run:
        workflows: ["Build DLL"]
        types:
            - completed

jobs:
    recalc:
        runs-on: ubuntu-latest
        timeout-minutes: 2
        steps:
            - name: Install doctl
              uses: digitalocean/action-doctl@v2
              with:
                  token: ${{ secrets.DIGITALOCEAN_TOKEN }}
            - name: Create deployment
              run: doctl apps create-deployment ${{ secrets.DIGITALOCEAN_APP_ID }}
